### ISSUE TITLE
APDU command chaining buffer buggy ?

### ISSUE THREAD

**Issue by DmxLarchey** [FluffyKaon/OpenPGP-Card#2]
Hi,

First of all, thx for sharing this project. I am trying to understand the logic behind the management of apdu command chaining in your applet. It seems to me that sometimes the chain is reinitialized when
it should not. I join a message I sent on the gnupg-users mailing list but I am more and more convinced that the problem I am spotting lies in the management of adpu chaining of your applet.

Basically, what I am able to reproduce is that in two consecutive decryption attempts of the same file (gpg -d), the second always fails unless some other commands are inserted in between the two attempts (like gpg --edit-card would produce) ... in the logs of scdaemon, it turns out that the decryption attempt produces a chain of 2 apdu (1 long, 1 very short). In the case of the second decryption attempt, the applet throws ISO7816.SW_WRONG_LENGTH before reading the remaining second APDU of the chain, hence the second APDU is not even sent to the applet of the JC.

Below some precise description of the problem,

Thx in advance for any hint on how to correct the problem.

DomLW

--------------------

Hi,

I am trying to setup a JavaCard (Gemalto IDCore 10 rev C) with
an OpenPGP applet. My goal is to obtain an equivalent of the
regular OpenPGP Smartcard (from ZeitControl) which I own as
well and which works perfectly (so far).

1/ I tried the Java Card OpenPGP Card (from joeridr) but it was
   impossible to either setup new PINS or verify the default
   one on that applet. Hopefully uninstalling and reinstalling
   the applet reinitialized both PINS retry counters to 3 ...
   At first I was afraid of bricking my JC.

   Btw the Yubikey Neo OpenPGP is nearly the same applet as
   the joeridr one ... doesn't even install on the JC.

2/ Then I tried the FluffyPGPApplet (from FluffyKaon) and with
   that one, I could setup new PIN and even check them ... gpg2
   basically worked but then I began to try the cryptographic
   functions of the card and a strange behavior appeared.

Indeed, the first decryption after a PIN check (either on the
JC hardware or simulated by edit-card verify) works whereas
subsequents decryption attempts fail.

Here is a sequence of commands that reproduce the problem.
Notice that scdaemon logs are attached below.

It seem to me that the apdu sequence sent on subsequent
decryption attempts are of the wrong length ...

Can anyone give my some hints as to want is going on ?

Thx very much in advance,

DomLW

---------------------

### first attempt, I am asked for the PIN (CHV1) and decryption is a success

$ gpg2 -d examples.desktop.asc > /dev/null
gpg: encrypted with 2048-bit RSA key, ID 04F53C66, created 2015-04-09
      "DomLW (test) <larchey@gmail.com>"

### probably because a too short apdu command is sent to the card (see the logs of scdaemon)

$ gpg2 -d examples.desktop.asc > /dev/null
gpg: encrypted with 2048-bit RSA key, ID 04F53C66, created 2015-04-09
      "DomLW (test) <larchey@gmail.com>"
gpg: public key decryption failed: Invalid value
gpg: decryption failed: No secret key

### first card-edit and verify the PIN, I am NOT asked for the PIN

$ gpg2 --card-edit

Application ID ...: D2760001240102000000000000000000
Version ..........: 2.0
Manufacturer .....: test card
Serial number ....: 00000000
Name of cardholder: Dominique Larchey-Wendling
Language prefs ...: fr
Sex ..............: male
URL of public key : [not set]
Login data .......: [not set]
Signature PIN ....: not forced
Key attributes ...: 2048R 2048R 2048R
Max. PIN lengths .: 32 32 32
PIN retry counter : 3 0 3
Signature counter : 3
Signature key ....: 3CB0 9186 9FD6 2670 085A  FA64 62FE A0E4 ED4D B6AB
      created ....: 2015-04-09 09:49:26
Encryption key....: C2B7 66F5 08A4 E8F5 C2B2  40C6 2F46 B077 04F5 3C66
      created ....: 2015-04-09 10:03:07
Authentication key: 0C69 4EE0 EB99 336D 75E9  C130 490C 3508 30DA 9738
      created ....: 2015-04-09 09:49:26
General key info..: [none]

gpg/card> verify

...

gpg/card> q

### this third decrypt does NOT ask for the PIN and succeeds

$ gpg2 -d examples.desktop.asc > /dev/null
gpg: encrypted with 2048-bit RSA key, ID 04F53C66, created 2015-04-09
      "DomLW (test) <larchey@gmail.com>"

------------

The logs of scdaemon (2048) during the previous sequence of commands
are accessible at https://gist.github.com/DmxLarchey/62abeaf53040b8c19cbb

**Comment by josecastillo** [comment]
I've been working on polishing up this application and I've noticed this bug as well. The issue is that after a successful decrypt, the command chaining buffer retains its state until a different INS is sent (see line 265). 

Each decipher command requires two APDUs to get all the data to the card. The first attempt sends 253 bytes of data in the first APDU, followed by 3 more in the second; the application detects that it has 256 bytes of data and performs the operation. The second attempt sends 253 more bytes of data, but since the state has been retained, the card application now thinks it has 509 bytes of data to decrypt and throws a "wrong length" exception (line 1083). This causes GnuPG to abort the attempt before it gets around to sending the last three bytes. 

This patch should fix the issue. It adds a line to the decrypt method that clears the command chaining buffer after a successful operation, as well as a return statement in the process method after a successful decrypt. This ensures that no state is retained in the command chaining buffer after a successful decryption operation. 

    diff --git a/java/net/ss3t/javacard/gpg/Gpg.java b/java/net/ss3t/javacard/gpg/Gpg.java
    index 8f2cd7f..36fcceb 100644
    --- a/java/net/ss3t/javacard/gpg/Gpg.java
    +++ b/java/net/ss3t/javacard/gpg/Gpg.java
    @@ -309,6 +309,7 @@ public final class Gpg extends Applet {
               computeSignature(apdu);
             } else if (p1p2 == (short) 0x8086) {
               decrypt(apdu);
    +          return; // After successful decryption, keep the command chaining buffer empty.
             } else {
               ISOException.throwIt(ISO7816.SW_INCORRECT_P1P2);
             }
    @@ -1095,6 +1096,8 @@ public final class Gpg extends Applet {
         cipherRSA.init(confidentialityKey.getPrivate(), Cipher.MODE_DECRYPT);
         len = cipherRSA.doFinal(commandChainingBuffer, TEMP_GET_RESPONSE_DATA, RSA_KEY_LENGTH_BYTES,
                                 buffer, (short) 0);
    +    // Clear command chaining buffer to make ready for next operation.
    +    Util.arrayFillNonAtomic(commandChainingBuffer, (short) 0, (short) commandChainingBuffer.length, (byte) 0);
         apdu.setOutgoingAndSend((short) 0, len);
       }
     
    --

**Comment by DmxLarchey** [comment]
Thank you very much for your answer. I will try the patch ASAP. I think indeed this is the same bug I am experiencing. Anyway since you are also involved in the ykneo OpenPGP  applet, I would like to ask you some further questions.

First, the command chaining management is, in my opinion, not very well written in the FullyKaon version. It is scattered all around in the different handlers for "ins" commands. It could be very hard to debug such a code. It is much cleaner in the legacy  javacard OpenPGP applet. Is there a document that describes the protocol for command chaining ? For instance, how to detect the end of a chain of commands (before receiving the first APDU of a new chain) ? Is command chaining "standardized" at all ?

I did try the legacy javacard OpenPGP applet from which the ykneo source code is derived. I was not able to change the PIN. After digging in the source code, I found that the APDU buffers are never filled using the apdu.setIncomingAndReceive() method. And indeed, when verifying the PIN, the default PIN is always checked against 00 00 00 00 00 00 which of course fails.

But I wonder how this code could have ever worked without any use of setIncomingAndReceive. Btw, it seems the Neo version of the applet does not use it either ? Is this method mandatory only for recent versions of the javacard API ? Is it related to extended APDUs ?

Anyway, thank you very much for our interaction so far.

Best,

**Comment by FluffyKaon** [comment]
Sorry about the bug and thank you for the patch. I would like to add some tests before integrating the patch in the code but it will take a bit of time since I am busy.
DmxLarchey: the smart card command chaining is described in the annex A of the ISO 7816-4 standard.
I agree that the extended APDU handling could use some love, it is always a trade off between memory usage, code size, clarity and time spent writing the code.

**Comment by DmxLarchey** [comment]
Dear josecastillo,

I can confirm that your patch removes the problem I was experiencing with two successive decryptions. However, I am still in doubt about the overall quality of the code for managing chained ADPU in the FluffyKaon applet.

**Comment by FluffyKaon** [comment]
Thank you Jose for the patch, it is applied and I added a test for it.
